"""create_user_s

Revision ID: be9c774e5c60
Revises: 9eb94ef43d46
Create Date: 2024-02-27 19:53:11.536040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be9c774e5c60'
down_revision: Union[str, None] = '9eb94ef43d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('access_token', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_index(op.f('ix_token_id'), 'token', ['id'], unique=False)
    op.drop_index('ix_basemodel_id', table_name='basemodel')
    op.drop_table('basemodel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basemodel',
    sa.Column('access_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='basemodel_pkey'),
    sa.UniqueConstraint('access_token', name='basemodel_access_token_key')
    )
    op.create_index('ix_basemodel_id', 'basemodel', ['id'], unique=False)
    op.drop_index(op.f('ix_token_id'), table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
